name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Build with Gradle
      run: |
        ./gradlew assembleDebug

    - name: Upload APK
      uses: 'https://github.com/actions/upload-artifact/releases/download/v3.1.2/upload-artifact-3.1.2.zip'
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk 